name: Generate PDF CV

on:
  push:
    paths:
      - "_pages/cv.md"
      - "assets/css/print.css"
      - ".github/workflows/generate-pdf.yml"
  workflow_dispatch:

jobs:
  export-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Wait for GitHub Pages to deploy
        run: sleep 60

      - name: Export CV page to PDF
        run: |
          chrome --headless --disable-gpu --print-to-pdf=CV_Jing-Yuan_Chen.pdf https://jychen74.github.io/cv/

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV_Jing-Yuan_Chen
          path: CV_Jing-Yuan_Chen.pdf
